# Generated by Django 3.1.5 on 2021-02-25 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttnapp', '0002_auto_20210225_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='marks',
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('marks', models.IntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_exam', to='ttnapp.subject')),
            ],
        ),
    ]
