# Generated by Django 3.1.5 on 2021-02-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttnapp', '0004_auto_20210226_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='marks',
            new_name='obtained_marks',
        ),
        migrations.AddField(
            model_name='exam',
            name='fullmarks',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='pic',
            field=models.ImageField(blank=True, default='ttnapp/static/img/uploads/368-kakashi.png', upload_to='uploads/'),
        ),
    ]
